version: '3.8'
services:
  flask:
    image: ${FLASK_IMAGE_NAME}
    build:
      context: .
      dockerfile: ${BUILD_FLASK_IMAGE}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}

  react:
    image: ${REACT_IMAGE_NAME}
    build:
      context: .
      dockerfile: ${BUILD_REACT_IMAGE}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    environment:
     - REACT_APP_API_URL=http://flask_api:8080 # URL to the Flask API

  r:
    image: ${R_IMAGE_NAME}
    build:
      context: .
      dockerfile: ${BUILD_R_IMAGE}
    ports:
      - "8787:8787"
    volumes:
      - ./r_scripts:/r_scripts