version: '3.8'
services:
  flask:
    image: ${FLASK_IMAGE_NAME}
    build:
      context: ./Flask
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Flask:/usr/src/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - R_API_URL=http://${R_HOST}:${R_PORT} # URL to the R API

  react:
    image: ${REACT_IMAGE_NAME}
    build:
      context: ./React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./React/client:/client
    environment:
     - REACT_APP_API_URL=http://${FLASK_RUN_HOST}:${FLASK_RUN_PORT} # URL to the Flask API

  r:
    image: ${R_IMAGE_NAME}
    build:
      context: ./R
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./R/r_scripts:/r_scripts
    environment:
      - R_HOST=${R_HOST}
      - R_PORT=${R_PORT}