version: "3.8"
services:
  flask:
    image: ${FLASK_IMAGE_NAME}
    build:
      context: ./app/flask-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/flask-api:/usr/src/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - R_API_URL=http://r:${R_PORT} # URL to the R API

  react:
    image: ${REACT_IMAGE_NAME}
    build:
      context: ./app/react-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/react-ui/client:/client
    environment:
      - REACT_APP_API_URL=http://flask:${FLASK_RUN_PORT} # URL to the Flask API

  r:
    image: ${R_IMAGE_NAME}
    build:
      context: ./app/r-plumber
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./app/r-plumber/r_scripts:/r_scripts
    environment:
      - R_HOST=${R_HOST}
      - R_PORT=${R_PORT}
