version: "3.8"
services:
  react:
    image: ${REACT_IMAGE_NAME}
    build:
      context: ./apps/react-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/react-ui/client:/client
    environment:
      - NEXT_PUBLIC_R_API_URL=http://r:${R_PORT} # URL to the R API

  r:
    image: ${R_IMAGE_NAME}
    build:
      context: ./apps/r-plumber
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./apps/r-plumber/r_scripts:/r_scripts
    environment:
      - R_HOST=${R_HOST}
      - R_PORT=${R_PORT}
