version: '3.8'
services:
  flask:
    image: ${FLASK_IMAGE_NAME}
    build:
      context: ./Flask-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Flask-app:/usr/src/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}

  react:
    image: ${REACT_IMAGE_NAME}
    build:
      context: ./React-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./React-client/client:/client
    environment:
     - REACT_APP_API_URL=http://flask_api:8080 # URL to the Flask API

  r:
    image: ${R_IMAGE_NAME}
    build:
      context: ./R
      dockerfile: Dockerfile
    ports:
      - "8787:8787"
    volumes:
      - ./R/r_scripts:/r_scripts