# Start with a base image that has R pre-installed
FROM r-base:latest

# Set the working directory in the container to /r_scripts
WORKDIR /r_scripts

# Copy the R scripts directory into the container
COPY ./r_scripts /r_scripts

# Run the packages.R file
RUN Rscript packages.R

# Keep the container running
CMD ["R"]
