# Use a Node base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /artma

# Copy package.json and package-lock.json
COPY artma/package*.json ./

# Install project dependencies
RUN npm install

# Copy the client directory contents into the container at /artma
COPY artma/ .

# Build the app
RUN npm run build

# Install serve to serve the static files
RUN npm install -g serve

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app
CMD ["serve", "-s", "build"]
