version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - r_service
    environment:
      - FLASK_ENV=development # Environment variables for Flask

  react:
    build:
      context: .
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    depends_on:
      - flask
    environment:
     - REACT_APP_API_URL=http://flask_api:5000 # URL to the Flask API

  r_service:
    build:
      context: .
      dockerfile: Dockerfile-r
    volumes:
      - ./r_scripts:/r_scripts
