const CONFIG = {
  BOOTSTRAP_ENABLED: false,
  WAIVE_ENABLED: false,
  SHOULD_USE_BOOTSTRAP_SE_AS_DEFAULT: false,
  SHOULD_ADD_CITATION_TO_FUNNEL_PLOT: true,
  SHOULD_SHOW_MODEL_PARAMS_HELP_MODAL: false,
  SHOULD_SHOW_DF_ROWS_INFO: true,
  SHOULD_SUGGEST_MOCK_DATA_USE: true,
  TOOLTIPS_ENABLED: {
    MODEL_PAGE: true,
    RESULTS_PAGE: true,
  },
} as const;

export default CONFIG;
