#!/bin/bash

# Development setup script for MAIVE UI
echo "Setting up development environment for MAIVE UI..."

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists. Backing up to .env.local.backup"
    cp .env.local .env.local.backup
fi

# Create .env.local with development configuration
cat > .env.local << EOF
# Development environment configuration for MAIVE UI
# This file is automatically generated by setup-dev.sh

# R API URL for development
# Default: localhost:8787 (for local R plumber server)
# Change this if you're using a different development server
NEXT_PUBLIC_DEV_R_API_URL=http://localhost:8787

# Uncomment and modify the line below if you want to use a remote development server
# NEXT_PUBLIC_DEV_R_API_URL=http://your-dev-server.com

# Whether to use mock data
NEXT_PUBLIC_USE_MOCK_DATA=false
EOF

echo "✅ .env.local created successfully!"
echo ""
echo "📝 Configuration:"
echo "   - R API URL: http://localhost:8787"
echo ""
echo "🔄 To start development:"
echo "   bun run dev"
echo ""
echo "🔧 To customize the R API URL, edit .env.local"
echo "   - For local development: NEXT_PUBLIC_DEV_R_API_URL=http://localhost:8787"
echo "   - For remote dev server: NEXT_PUBLIC_DEV_R_API_URL=http://your-server.com"
echo ""
echo "📚 For more information, see env.example"
